name: React CI with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Replace with the version of Node.js you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run tests and generate coverage report
      - name: Run tests and collect coverage
        run: |
          npm test -- --coverage --watchAll=false

      # Step 5: Upload the coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage/  # Ensure this path points to your coverage folder

      # Optional: Step 6 to publish coverage to Codecov
      # Uncomment the following section if you want to upload coverage to Codecov
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     file: ./coverage/lcov-report/index.html  # Modify if needed to match your coverage report

